name: rainix-rs
on: [push]
jobs:
  static:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-static.yaml@main
  test:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-test.yaml@main
  js-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
      - run: nix develop -c build-js-bindings
      - run: nix develop -c test-js-bindings
      - run: nix develop -c js-bindings-docs
